apiVersion: v1
kind: Service
metadata:
  name: ddp-hs
  namespace: ai-lab
  labels:
    app: ddp
    type: headless-service
spec:
  clusterIP: None
  selector:
    app: ddp
  ports:
  - name: rdzv
    port: 29400
    targetPort: 29400