apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcgm-exporter
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    app: dcgm-exporter
spec:
  selector:
    matchLabels:
      app: dcgm-exporter
  template:
    metadata:
      labels:
        app: dcgm-exporter
    spec:
      serviceAccountName: dcgm-exporter
      hostNetwork: true
      containers:
      - name: dcgm-exporter
        image: nvidia/dcgm-exporter:3.2.6-3.2.3-ubuntu20.04
        args:
          - "-f"
          - "/etc/dcgm-exporter/dcp-metrics-included.csv"
        ports:
        - name: metrics
          containerPort: 9400
          hostPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/dcgm-exporter
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: config
        configMap:
          name: dcgm-exporter-config
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      - operator: Exists
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dcgm-exporter-config
  namespace: kube-system
data:
  dcp-metrics-included.csv: |
    # Format: [Metric Name], [Metric Type], [Description]
    DCGM_FI_DEV_GPU_UTIL, gauge, GPU utilization
    DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory copy utilization
    DCGM_FI_DEV_XID_ERRORS, gauge, XID errors
    DCGM_FI_PROF_GR_ENGINE_ACTIVE, gauge, Graphics engine active
---
apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: kube-system
  labels:
    app: dcgm-exporter
spec:
  selector:
    app: dcgm-exporter
  ports:
  - port: 9400
    targetPort: 9400
    name: metrics