apiVersion: v1
kind: Pod
metadata:
  name: mig-test
  labels:
    app: mig-test
spec:
  restartPolicy: Never
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.2.1
    resources:
      limits:
        nvidia.com/gpu: 1
    command: 
      - "/bin/bash"
      - "-c"
      - |
        nvidia-smi
        echo "MIG instance allocated successfully!"
        sleep 3600
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
  nodeSelector:
    # Adjust based on your node labels
    kubernetes.io/hostname: gpu-node-1