apiVersion: v1
kind: Pod
metadata:
  name: mig-test
  labels:
    app: mig-test
spec:
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda11.2.0
    resources:
      limits:
        nvidia.com/gpu: 1
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done"]
  restartPolicy: Never