apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddp-outputs
  namespace: ai-lab
  labels:
    app: ddp-training
    type: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Adjust based on your cluster