name: "my_model"
platform: "pytorch_libtorch"
max_batch_size: 8

input [
    {
        name: "INPUT__0"
        data_type: TYPE_FP32
        dims: [3, 32, 32]
    }
]

output [
    {
        name: "OUTPUT__0"
        data_type: TYPE_FP32
        dims: [10]
    }
]

instance_group [
    {
        kind: KIND_GPU
        count: 1
    }
]

dynamic_batching {
    max_queue_delay_microseconds: 100
}